### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by melerpe** [OpenAudioMc/OpenAudioAPP#1]
On android (Maybe other platforms) soundmanager fails to play a sound!
What can cause it (It seems playing an ogg doesn't work. Other soundmanager needed??

**Comment by Mindgamesnl** [comment]
Soundmanager uses some fancy functions in browsers (sometimes even flash when needed (like pan))

On what platform is the app made?

**Comment by melerpe** [comment]
We use Phonegap [JS + HTML +CSS], it connects to the socket.io server without any problems, setting volume works! And also the background.

**Comment by Mindgamesnl** [comment]
Try using the Cordova Native Audio Plugin

**Comment by melerpe** [comment]
Yeey, a rewrite. [If it gets the music working I will try my best!!]
